version: '2'

services:
  web:
    image: eu.gcr.io/rdx-net-public-registry/apache2.4-php7.4:${IMAGE_TAG:-latest}
    build:
      context: .
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./volumes/a-shared
        target: /a/shared
