version: '2'

services:
  web:
    # image: 'todo'
    build:
      context: .
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: ./volumes/a-shared
        target: /a/shared
